addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.16")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.24")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.6.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.7.6")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"         % "0.6.1")
