addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.9.31")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.6.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"      % "1.5.7")
