---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    tags:
    - v*

jobs:
  checks:
    name: Format and style checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v7
      with:
        java-version: adopt@1.11
    - run: sbt publish bintraySyncMavenCentral
