---
name: publish

on:  # yamllint disable-line rule:truthy
  push:
    tags:
    - v*

jobs:
  checks:
    name: Publish to maven central
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.11
    - run: sbt publish bintraySyncMavenCentral
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
        SONA_USER: ${{ secrets.SONA_USER }}
        SONA_PASS: ${{ secrets.SONA_PASS }}
